// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALdzT5guba0_EtxI-TIeAR_E03mZp3bv8',
    appId: '1:833944674779:web:8babd0a66a4ea2398807fe',
    messagingSenderId: '833944674779',
    projectId: 'pfinanciero-a79c9',
    authDomain: 'pfinanciero-a79c9.firebaseapp.com',
    storageBucket: 'pfinanciero-a79c9.firebasestorage.app',
    measurementId: 'G-JWNETW8JKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAN0v4VR2faJBhohucMI4Hb0R5vY-Itww',
    appId: '1:833944674779:android:20f178ce57f8a95e8807fe',
    messagingSenderId: '833944674779',
    projectId: 'pfinanciero-a79c9',
    storageBucket: 'pfinanciero-a79c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxW-_Iq5QbzwYGSLe8D74x5kTQh4GAqPs',
    appId: '1:833944674779:ios:c4efb3fbaec370138807fe',
    messagingSenderId: '833944674779',
    projectId: 'pfinanciero-a79c9',
    storageBucket: 'pfinanciero-a79c9.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinanciero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxW-_Iq5QbzwYGSLe8D74x5kTQh4GAqPs',
    appId: '1:833944674779:ios:c4efb3fbaec370138807fe',
    messagingSenderId: '833944674779',
    projectId: 'pfinanciero-a79c9',
    storageBucket: 'pfinanciero-a79c9.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinanciero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALdzT5guba0_EtxI-TIeAR_E03mZp3bv8',
    appId: '1:833944674779:web:8e9197678962bbed8807fe',
    messagingSenderId: '833944674779',
    projectId: 'pfinanciero-a79c9',
    authDomain: 'pfinanciero-a79c9.firebaseapp.com',
    storageBucket: 'pfinanciero-a79c9.firebasestorage.app',
    measurementId: 'G-7M7QMWF2K8',
  );
}
